INSERT INTO clients(name, surname, email, created_at) VALUES ('Antonio', 'Lopez Guzmán', 'alg@gmail.com', '2012-01-29');
INSERT INTO clients(name, surname, email, created_at) VALUES ('Laura', 'Martin Bonilla', 'lmb@gmail.com', '2015-06-2');
INSERT INTO clients(name, surname, email, created_at) VALUES ('María', 'Guzmán García', 'lmb@gmail.com', '2015-06-2');
INSERT INTO clients(name, surname, email, created_at) VALUES ('Miguel', 'de los Ángeles Gutierrez', 'lmb@gmail.com', '2015-06-2');
INSERT INTO clients(name, surname, email, created_at) VALUES ('Pablo', 'Escobar Arroba', 'lmb@gmail.com', '2015-06-2');
INSERT INTO clients(name, surname, email, created_at) VALUES ('Raúl', 'Jimenez de la Serna', 'lmb@gmail.com', '2015-06-2');
INSERT INTO clients(name, surname, email, created_at) VALUES ('Ainara', 'Villa Hoz', 'lmb@gmail.com', '2015-06-2');
INSERT INTO clients(name, surname, email, created_at) VALUES ('Segismundo', 'Madrid Cid', 'lmb@gmail.com', '2015-06-2');
INSERT INTO clients(name, surname, email, created_at) VALUES ('Prudencio', 'Delgado Díaz', 'lmb@gmail.com', '2015-06-2');
INSERT INTO clients(name, surname, email, created_at) VALUES ('Tomás', 'Lobo Bueno', 'lmb@gmail.com', '2015-06-2');
INSERT INTO clients(name, surname, email, created_at) VALUES ('Antonio', 'Lopez Guzmán', 'alg@gmail.com', '2012-01-29');
INSERT INTO clients(name, surname, email, created_at) VALUES ('Laura', 'Martin Bonilla', 'lmb@gmail.com', '2015-06-2');
INSERT INTO clients(name, surname, email, created_at) VALUES ('María', 'Guzmán García', 'lmb@gmail.com', '2015-06-2');
INSERT INTO clients(name, surname, email, created_at) VALUES ('Miguel', 'de los Ángeles Gutierrez', 'lmb@gmail.com', '2015-06-2');
INSERT INTO clients(name, surname, email, created_at) VALUES ('Pablo', 'Escobar Arroba', 'lmb@gmail.com', '2015-06-2');
INSERT INTO clients(name, surname, email, created_at) VALUES ('Raúl', 'Jimenez de la Serna', 'lmb@gmail.com', '2015-06-2');
INSERT INTO clients(name, surname, email, created_at) VALUES ('Ainara', 'Villa Hoz', 'lmb@gmail.com', '2015-06-2');
INSERT INTO clients(name, surname, email, created_at) VALUES ('Segismundo', 'Madrid Cid', 'lmb@gmail.com', '2015-06-2');
INSERT INTO clients(name, surname, email, created_at) VALUES ('Prudencio', 'Delgado Díaz', 'lmb@gmail.com', '2015-06-2');
INSERT INTO clients(name, surname, email, created_at) VALUES ('Tomás', 'Lobo Bueno', 'lmb@gmail.com', '2015-06-2');
INSERT INTO clients(name, surname, email, created_at) VALUES ('Tomás', 'Lobo Bueno', 'lmb@gmail.com', '2015-06-2');
INSERT INTO clients(name, surname, email, created_at) VALUES ('Laura', 'Martin Bonilla', 'lmb@gmail.com', '2015-06-2');
INSERT INTO clients(name, surname, email, created_at) VALUES ('María', 'Guzmán García', 'lmb@gmail.com', '2015-06-2');
INSERT INTO clients(name, surname, email, created_at) VALUES ('Miguel', 'de los Ángeles Gutierrez', 'lmb@gmail.com', '2015-06-2');
INSERT INTO clients(name, surname, email, created_at) VALUES ('Pablo', 'Escobar Arroba', 'lmb@gmail.com', '2015-06-2');
INSERT INTO clients(name, surname, email, created_at) VALUES ('Raúl', 'Jimenez de la Serna', 'lmb@gmail.com', '2015-06-2');
INSERT INTO clients(name, surname, email, created_at) VALUES ('Ainara', 'Villa Hoz', 'lmb@gmail.com', '2015-06-2');
INSERT INTO clients(name, surname, email, created_at) VALUES ('Segismundo', 'Madrid Cid', 'lmb@gmail.com', '2015-06-2');
INSERT INTO clients(name, surname, email, created_at) VALUES ('Prudencio', 'Delgado Díaz', 'lmb@gmail.com', '2015-06-2');
INSERT INTO clients(name, surname, email, created_at) VALUES ('Tomás', 'Lobo Bueno', 'lmb@gmail.com', '2015-06-2');
INSERT INTO clients(name, surname, email, created_at) VALUES ('Antonio', 'Lopez Guzmán', 'alg@gmail.com', '2012-01-29');
INSERT INTO clients(name, surname, email, created_at) VALUES ('Laura', 'Martin Bonilla', 'lmb@gmail.com', '2015-06-2');
INSERT INTO clients(name, surname, email, created_at) VALUES ('María', 'Guzmán García', 'lmb@gmail.com', '2015-06-2');
INSERT INTO clients(name, surname, email, created_at) VALUES ('Miguel', 'de los Ángeles Gutierrez', 'lmb@gmail.com', '2015-06-2');
INSERT INTO clients(name, surname, email, created_at) VALUES ('Pablo', 'Escobar Arroba', 'lmb@gmail.com', '2015-06-2');
INSERT INTO clients(name, surname, email, created_at) VALUES ('Raúl', 'Jimenez de la Serna', 'lmb@gmail.com', '2015-06-2');
INSERT INTO clients(name, surname, email, created_at) VALUES ('Ainara', 'Villa Hoz', 'lmb@gmail.com', '2015-06-2');
INSERT INTO clients(name, surname, email, created_at) VALUES ('Segismundo', 'Madrid Cid', 'lmb@gmail.com', '2015-06-2');
INSERT INTO clients(name, surname, email, created_at) VALUES ('Prudencio', 'Delgado Díaz', 'lmb@gmail.com', '2015-06-2');
